### PR TITLE
[WIP] Documentation for focused specs.

### PR DESCRIPTION
**Pull request by ezzatron**
Related documentation for peridot-php/peridot#185 and peridot-php/peridot#197.

### CODE REVIEW

**Comment by ezzatron** [comment]
@brianium I couldn't resist fixing up some other minor issues while I was making this change. It's a bit crufty from that perspective, but it's all stuff I would have liked to fix up before a release anyway.

A list of additional stuff in this PR, in no particular order:

- Fixed a CSS issue with dot point lists, where the list item content would appear below the list item dot.
- Utilized `{% highlight php startinline %}` where possible, and removed `<?php` and `?>` where appropriate for succinctness.
- Updated the `composer require` install instructions, as the version number is not required / actually detrimental in the most common case, where users just want the latest version.
- Updated the entire CLI options documentation section, and attempted to order it in terms of most commonly used options.

**Comment by brianium** [comment]
Dannnnnng. Good work man. I didn't know about `{% highlight php startinline %}`

I'm comfortable with all of these changes. Pretty excited about this next release man :)

**Comment by brianium** [comment]
I se the [WIP] title on here, so I won't merge quite yet. Let me know when you have things where you want them. Thanks!

**Comment by ezzatron** [comment]
@brianium Awesome man, I'm pretty stoked too :)

I'll squash the commits now. If we merge these into master, does it immediately become public? If that's the case, we should probably wait until we make the actual release, yeah?

**Comment by brianium** [comment]
@ezzatron I believe it does become public, so I will hold off on the merge for now.

**Pull request merged**
